image: elixir:1.4

services:
  - mdillon/postgis:9.6-alpine

variables:
  MIX_ENV: "test"
  POSTGRES_DB: eventos_test
  POSTGRES_USER: ci
  POSTGRES_PASSWORD: test


cache:
  key: "$CI_JOB_NAME"
  paths:
    - deps
    - _build
    - .rebar3

before_script:
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

mix:
  script:
  - mix credo || true
  - mix test
