image: tcitworld/mobilizon-ci

services:
  - name: mdillon/postgis:10
    alias: postgres

variables:
  MIX_ENV: "test"
  POSTGRES_DB: mobilizon_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres
  GEOLITE_CITIES_PATH: "/usr/share/GeoIP/GeoLite2-City.mmdb"

cache:
  paths:
    - deps
    - _build
    - .rebar3
    - ~/.mix
    - ~/.hex
    - js/node_modules

before_script:
  - cd js && npm install && npm run build && cd ../
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

mix:
  script:
  - mix format --check-formatted --dry-run
  - mix coveralls
