image: elixir:1.6

services:
  - name: mdillon/postgis:9.6
    alias: postgres

variables:
  MIX_ENV: "test"
  POSTGRES_DB: eventos_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres

cache:
  key: "$CI_JOB_NAME"
  paths:
    - deps
    - _build
    - .rebar3

before_script:
  - apt-get update
  - apt-get install -y build-essential postgresql-client git
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
  - curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz --output priv/static/GeoLite2-City.mmdb -s

mix:
  script:
  - mix credo
  - mix coveralls
