image: elixir:latest

services:
  - mdillon/postgis:9.6-alpine

variables:
  MIX_ENV: "test"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - deps
    - _build
    - .rebar3

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

mix:
  script:
  - mix credo || true
  - mix test
