image: elixir:1.4

services:
  - mdillon/postgis:9.6

variables:
  MIX_ENV: "test"
  POSTGRES_DB: eventos_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: mdillon-postgis

cache:
  key: "$CI_JOB_NAME"
  paths:
    - deps
    - _build
    - .rebar3

before_script:
  - apt-get update
  - apt-get install -y build-essential postgresql-client git
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

mix:
  script:
  - mix credo || true
  - mix test
