version: "3"

services:
  mobilizon:
    image: mobilizon
    environment:
      - MOBILIZON_INSTANCE_NAME
      - MOBILIZON_INSTANCE_HOST
      - MOBILIZON_INSTANCE_EMAIL
      - MOBILIZON_REPLY_EMAIL
      - MOBILIZON_INSTANCE_REGISTRATIONS_OPEN=true
      - MOBILIZON_DATABASE_USERNAME=${POSTGRES_USER}
      - MOBILIZON_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - MOBILIZON_DATABASE_DBNAME=${POSTGRES_DB}
      - MOBILIZON_DATABASE_HOST=db
      - MOBILIZON_INSTANCE_SECRET_KEY_BASE
      - MOBILIZON_INSTANCE_SECRET_KEY
      - MOBILIZON_SMTP_SERVER=yoursmtpserver
      - MOBILIZON_SMTP_HOSTNAME=your.smtp.domain
      - MOBILIZON_SMTP_USERNAME
      - MOBILIZON_SMTP_PASSWORD
    volumes:
      - /tmp/public/upload:/app/upload
    ports:
     - "4000:4000"

  db:
    image: postgis/postgis
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

networks:
  default:
    ipam:
      driver: default
