version: '3'

services:

  postgres:
    container_name: mobilizon_db
    restart: unless-stopped
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobilizon_dev

  front:
    container_name: mobilizon_front
    restart: unless-stopped
    build: ./js
    volumes:
      - './js:/app/js'
    ports:
      - "8888:8080"
    entrypoint: entrypoint

  api:
    container_name: mobilizon_api
    restart: unless-stopped
    build: .
    volumes:
      - '.:/app'
    ports:
      - "4000:4001"
    depends_on:
      - postgres
    environment:
      # Environment: Prod when ready
      MIX_ENV: dev
      # Instance
      MOBILIZON_INSTANCE_NAME: My Mobilizon Instance
      MOBILIZON_INSTANCE_HOST: mobilizon.me
      MOBILIZON_INSTANCE_EMAIL: noreply@mobilizon.me
      MOBILIZON_INSTANCE_REGISTRATIONS_OPEN: "false"
      MOBILIZON_DATABASE_PASSWORD: postgres
      MOBILIZON_DATABASE_USERNAME: postgres
      MOBILIZON_DATABASE_DBNAME: mobilizon_dev
      MOBILIZON_DATABASE_HOST: postgres
    entrypoint: entrypoint
